name: Nominatim-app workflow
on: [push]
jobs:
   tests:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
           python-version: 3.7
      - name: Install dependencies
        run: |
           python3 -m pip install --upgrade pip
           pip3 install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
           pip3 install -r requirements.txt
      - name: Test with flake8
        run:
           flake8 ./tests/ --ignore E501,E126,N400
      - name: Test with pytest
        run:
           pytest -s -v ./tests